name: Code Scanning (Semgrep)
description: "Runs a Semgrep scan on a repository and uploads the results to GitHub"

inputs:
  defectdojo_token:
    description: "Token to use to submit data to DefectDojo"
    required: true
  defectdojo_host:
    description: "Hostname of DefectDojo"
    required: true
  defectdojo_product_name:
    description: "Product name"
    required: false
    default: "github"
  defectdojo_engagement_name:
    description: "Engagement name"
    required: false
    default: "github"
  paths_ignored:
    description: "List of paths or patterns to ignore"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: DefectDojo create engagement
      id: create_engagement
      shell: bash
      run: |
        ENGAGEMENT_ID=$(curl -s -X POST -H "Content-Type: application/json" \
          -H "Authorization: Token ${{ inputs.defectdojo_token }}" \
          -d "{
            \"name\": \"${{ inputs.defectdojo_engagement_name }}\",
            \"product\": \"${{ inputs.defectdojo_product_name }}\",
            \"status\": \"In Progress\",
            \"target_start\": \"$(date -Iseconds)\",
            \"target_end\": \"$(date -Iseconds)\"
          }" \
          "https://${{ inputs.defectdojo_host }}/api/v2/engagements/" \
          | jq -r '.id')
        echo "Created engagement ID: $NEW_ENG_ID"
        echo "engagement_id=$NEW_ENG_ID" >> $GITHUB_OUTPUT

    - name: Semgrep scan
      run: |
        echo "${{ inputs.paths_ignored }}" > .semgrepignore
        semgrep \
          --config p/default \
          --config p/owasp-top-ten \
          --config p/security-audit \
          --config p/ci \
          --config p/csharp \
          --config ${{ github.action_path }}/rules/src \
          --verbose --metrics=off --force-color \
          --json-output semgrep-report.json
      shell: bash
      continue-on-error: true

    - name: DefectDojo upload semgrep findings
      shell: bash
      run: |
        curl -sS -X POST \
          -H "Authorization: Token ${{ inputs.defectdojo_token }}" \
          -F "file=@semgrep-report.json" \
          -F "scan_type=Semgrep JSON Report" \
          -F "product_name=${{ inputs.defectdojo_product_name }}" \
          -F "engagement_name=${{ inputs.defectdojo_engagement_name }}" \
          "https://${{ inputs.defectdojo_host }}/api/v2/import-scan/"

    - name: DefectDojo update engagement status
      shell: bash
      run: |
        echo "Marking engagement $ENGAGEMENT_ID as Completed..."
        curl -s -X PATCH -H "Content-Type: application/json" \
          -H "Authorization: Token ${{ inputs.defectdojo_token }}" \
          -d '{"status": "Completed"}' \
          "https://${{ inputs.defectdojo_host }}/api/v2/engagements/${{ steps.create_engagement.engagement_id }}"

