name: Code Scanning (Semgrep)
description: "Runs a Semgrep scan on a repository and uploads the results to GitHub"

inputs:
  paths_ignored:
    description: "List of paths or patterns to ignore"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate .semgrepignore
      run: |
        echo "${{ inputs.paths_ignored }}" > .semgrepignore
        cat .semgrepignore
      shell: bash

    - name: Semgrep
      run: |
        semgrep \
          --config p/default \
          --config p/owasp-top-ten \
          --config p/security-audit \
          --config p/ci \
          --config p/csharp \
          --config ${{ github.action_path }}/rules/src \
          --verbose --metrics=off --force-color \
          --json-output semgrep-report.json
      shell: bash
      continue-on-error: true

    - name: Upload to DefectDojo
      run: |
        curl -sS -X POST \
          -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
          -F "file=@semgrep-report.json" \
          -F "scan_type=Semgrep JSON Report" \
          https://defectdojo.lb-admin.dev/api/v2/import-scan/
      env:
        DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}

