name: Code Scanning (Semgrep)
description: "Runs a Semgrep scan on a repository and uploads the results to GitHub"

inputs:
  paths_ignored:
    description: "List of paths or patterns to ignore"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Semgrep scan
      run: |
        echo "${{ inputs.paths_ignored }}" > .semgrepignore
        semgrep \
          --config p/default \
          --config p/owasp-top-ten \
          --config p/security-audit \
          --config p/ci \
          --config p/csharp \
          --config ${{ github.action_path }}/rules/src \
          --verbose --metrics=off --force-color \
          --json-output semgrep.json
      shell: bash
      continue-on-error: true
