name: Code Scanning (Semgrep)
description: "Runs a Semgrep scan on a repository and uploads the results to GitHub"

inputs:
  paths_ignored:
    description: "List of paths or patterns to ignore"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        apt install -y python3-pip

    - name: Install Semgrep
      run: |
        pip install semgrep
      shell: bash

    - name: Generate .semgrepignore
      run: |
        echo "${{ inputs.paths_ignored }}" > .semgrepignore
        cat .semgrepignore
      shell: bash

    - name: Run Semgrep Scan
      run: |
        echo "::group::Semgrep Security Scan"
        semgrep --config p/default --config p/owasp-top-ten --config p/security-audit --config p/ci --config p/csharp --config ${{ github.action_path }}/rules/src --verbose --metrics=off
        # --output semgrep-results.sarif --sarif --verbose
        echo "::endgroup::"
      shell: bash
      continue-on-error: true

# This requires full GHAS Code Scanning enabled for the repo.
# watch your money burn!
#
#    - name: Upload Semgrep Results to GitHub
#      uses: github/codeql-action/upload-sarif@v3
#      with:
#        sarif_file: semgrep-results.sarif
